version: "2"
run:
  concurrency: 4
  timeout: 3m
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - durationcheck
    - errcheck
    - errorlint
    - forbidigo
    - gosec
    - govet
    - nilerr
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - whitespace
  settings:
    forbidigo:
      forbid:
        - pattern: ^(fmt\.Print.*|print|println)$
        - pattern: ^spew\.Dump$
        - pattern: ^pp\.(P|PP|Sp|Fp)rint?$
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: (.*)should have comment(.+)or be unexported|comment(.+)should be of the form
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
