name: Check & test & build
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    name: Quality & security checks
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'
          check-latest: true

      - name: Check out code
        uses: actions/checkout@v3

      - name: Lint Go Code
        run: make check

  test:
    name: Test & coverage
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'
          check-latest: true

      - name: Check out code
        uses: actions/checkout@v3

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0

      - name: Run unit tests with
        run: make test